services:
  - type: web
    name: google-login-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
